name: TelegramBots:branch-2

on:
  pull_request:
    branches:
      branch-2
  push:
    branches:
    - branch-2

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: 11
      - name: Test
        run: |
          mvn -q install -Dgpg.skip
          mvn -q clean compile test
          bash <(curl -s https://codecov.io/bash)
