on:
  push:
    branches:
      master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDKs
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: 11
    - name: Install dependencies
      run: mvn -q install -Dgpg.skip
    - name: Build with Maven
      run: mvn -q clean compile test
    - name: Curl Codecov
      if: ${{ success() }}
      run: bash <(curl -s https://codecov.io/bash)
        
